version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${MOODLE_DATABASE_USER}
      - MARIADB_PASSWORD=${MOODLE_DATABASE_PASSWORD}
      - MARIADB_DATABASE=moodle_mariadb
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/moodle/mariadb'
  moodle:
    image: 'docker.io/bitnami/moodle:latest'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
      - MOODLE_DATABASE_NAME=moodle_mariadb
      - MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_PASSWORD}
      - MOODLE_USER=${MOODLE_USER}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_SITE_NAME=${MOODLE_SITE_NAME}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/moodle/moodle'
      - 'moodledata_data:/moodle/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
